/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author edenj
 */
public class JDialogCarritoAgregarProducto extends javax.swing.JDialog {

    int posProducto = -1;
    String nombreProducto = "";
    double precio = 0;
    ArrayList <clases.Producto> productos;
    clases.Mesa mesa;
    String categorias[];
    /**
     * Creates new form JDialogCarritoAgregarProducto
     */
    public JDialogCarritoAgregarProducto(java.awt.Frame parent, boolean modal, clases.Mesa mesa, ArrayList <clases.Producto> productos, String categorias[]) {
        super(parent, modal);
        this.mesa = mesa;
        this.productos = productos;
        this.categorias = categorias;
        initComponents();
        llenarCategorias();
        jTableProductos.clearSelection();
        jTableProductos.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelCategoria = new javax.swing.JLabel();
        jTextFieldProductoNombre = new javax.swing.JTextField();
        jLabelProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonAgregar = new javax.swing.JButton();
        jLabelCantidad = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBoxCategoria.setFont(new java.awt.Font("Consolas", 2, 16)); // NOI18N
        jComboBoxCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCategoriaItemStateChanged(evt);
            }
        });

        jLabelCategoria.setFont(new java.awt.Font("Consolas", 2, 16)); // NOI18N
        jLabelCategoria.setText("Categoría: ");

        jTextFieldProductoNombre.setFont(new java.awt.Font("Consolas", 2, 16)); // NOI18N
        jTextFieldProductoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProductoNombreKeyTyped(evt);
            }
        });

        jLabelProducto.setFont(new java.awt.Font("Consolas", 2, 15)); // NOI18N
        jLabelProducto.setText("Producto: ");

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jTableProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableProductosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        jButtonAgregar.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jLabelCantidad.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jLabelCantidad.setText("Cantidad:");

        jSpinnerCantidad.setFont(new java.awt.Font("Consolas", 2, 15)); // NOI18N
        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinnerCantidad.setToolTipText("Cantidad del Producto seleccionado");
        jSpinnerCantidad.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerCantidad, ""));
        jSpinnerCantidad.setValue(1);
        jSpinnerCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCantidadStateChanged(evt);
            }
        });

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTotal.setText("$ 0.00");

        jLabelTotal.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jLabelTotal.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProducto)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAgregar))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCantidad)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCategoria))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProducto))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidad)
                    .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProductoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProductoNombreKeyTyped
        posProducto = herramientas.ManipulaCarrito.buscaProducto(jTableProductos, jTextFieldProductoNombre.getText());
        jTableProductosMouseClicked(null);
    }//GEN-LAST:event_jTextFieldProductoNombreKeyTyped

    private void jComboBoxCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaItemStateChanged
        herramientas.ManipulaCarrito.obtenerProductoCategoria(jComboBoxCategoria.getSelectedItem().toString(), jTableProductos, productos);
        jTableProductosMouseClicked(null);
    }//GEN-LAST:event_jComboBoxCategoriaItemStateChanged

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        int fila = jTableProductos.getSelectedRow();
        if (fila >= 0) {
            String costoUnitario = jTableProductos.getModel().getValueAt(fila, 1).toString();
            nombreProducto = jTableProductos.getModel().getValueAt(fila, 0).toString();
            precio = Double.parseDouble(costoUnitario);
            int cantidad = Integer.parseInt(jSpinnerCantidad.getModel().getValue().toString());
            jTextFieldTotal.setText("$ " + (precio * cantidad));
        } else {
            jTextFieldTotal.setText("$ 0.00");
            nombreProducto = "";
            precio = 0;
        }
    }//GEN-LAST:event_jTableProductosMouseClicked

    private void jSpinnerCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCantidadStateChanged
        jTableProductosMouseClicked(null);
    }//GEN-LAST:event_jSpinnerCantidadStateChanged

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        jTableProductosMouseClicked(null);
        int pos = herramientas.ManipulaMesas.posProducto(mesa, nombreProducto);
        int cantidad = Integer.parseInt(jSpinnerCantidad.getModel().getValue().toString());
        if (pos != -1) {
            clases.ProductoVenta productoTmp = mesa.getProductos().get(pos);
            productoTmp.setCantidad(productoTmp.getCantidad() + cantidad);
            JOptionPane.showMessageDialog(this, "El producto ya estaba en la lista, se agregó la cantidad");
        } else if (!nombreProducto.isEmpty()) {
            mesa.getProductos().add(new clases.ProductoVenta(nombreProducto, precio, cantidad));
            JOptionPane.showMessageDialog(this, "El producto se agregó a la lista con éxito");
        } else {
            JOptionPane.showMessageDialog(this, "Favor de tener seleccionado el producto a agregar");
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTableProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProductosKeyReleased
        jTableProductosMouseClicked(null);
    }//GEN-LAST:event_jTableProductosKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldProductoNombre;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
    void llenarCategorias() {
        herramientas.ManipulaCarrito.llenarCombo(categorias, jComboBoxCategoria);
    }
}
