/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import cjb.ci.Validaciones;
import herramientas.ManipulaEmpleados;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class JDialogLoginEmpleado extends javax.swing.JDialog {
    
    ArrayList <clases.Empleado> empleados;
    DateTimeFormatter hora = DateTimeFormatter.ofPattern("HH:mm");
    /**
     * Creates new form NewJDialog
     */
    public JDialogLoginEmpleado(java.awt.Frame parent, boolean modal, ArrayList <clases.Empleado> empleados) {
        super(parent, modal);
        this.empleados = empleados;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxEmpleados = new javax.swing.JComboBox<>();
        jLabelPin = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Empleado:");

        jLabelPin.setText("Pin:");

        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPin)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxEmpleados, 0, 137, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButtonIngresar)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPin)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonIngresar)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        llenarEmpleados();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        String pin = jPasswordField1.getText();
        String nombre = (String) jComboBoxEmpleados.getSelectedItem();
        if (pin.length() != 0) {
            if (ManipulaEmpleados.ConsultaIngreso(empleados, nombre)) {
                JOptionPane.showMessageDialog(this, "El empleado ya ha ingresado a turno");
            } else {
                String h = hora.format(LocalDateTime.now());
                if (ManipulaEmpleados.ingresarEmpleado(empleados, nombre, Integer.valueOf(pin), h)) {
                    int ret = ManipulaEmpleados.ConsultaRetardos(empleados, nombre);
                    JOptionPane.showMessageDialog(this, "Ingreso exitoso " + nombre + "\nHora: " + h + "\nRetardos: " + ret);
                } else {
                    JOptionPane.showMessageDialog(this, "PIN invalido, por favor ingrese de nuevo");
                }
                jPasswordField1.setText("");
            }
        }
        pin = "";
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String pin = jPasswordField1.getText();
            String nombre = (String) jComboBoxEmpleados.getSelectedItem();
            if (pin.length() != 0) {
                if (ManipulaEmpleados.ConsultaIngreso(empleados, nombre)) {
                    JOptionPane.showMessageDialog(this, "El empleado ya ha ingresado a turno");
                } else {
                    String h = hora.format(LocalDateTime.now());
                    if (ManipulaEmpleados.ingresarEmpleado(empleados, nombre, Integer.valueOf(pin), h)) {
                        int ret = ManipulaEmpleados.ConsultaRetardos(empleados, nombre);
                        JOptionPane.showMessageDialog(this, "Ingreso exitoso " + nombre + "\nHora: " + h + "\nRetardos: " + ret);
                    } else {
                        JOptionPane.showMessageDialog(this, "PIN invalido, por favor ingrese de nuevo");
                    }
                    jPasswordField1.setText("");
                }
            }
            pin = "";
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jPasswordField1KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JComboBox<String> jComboBoxEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPin;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
    void llenarEmpleados() {
        herramientas.ManipulaEmpleados.llenarCombo(empleados, jComboBoxEmpleados);
    }
}
