/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import herramientas.ManipulaArchivos;
import herramientas.ManipulaCarrito;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class JDialogAgregaProducto extends javax.swing.JDialog {

    ArrayList <clases.Producto> productos;
    String categorias[];
    int opcion;
    String nombre;
    Frame ventana;
    /**
     * Creates new form JDialogAgregaProducto
     */
    public JDialogAgregaProducto(java.awt.Frame parent, boolean modal, ArrayList <clases.Producto> productos, String categorias[], int opcion, String nombre) {
        super(parent, modal);
        this.productos = productos;
        this.categorias = categorias;
        this.opcion = opcion;
        this.nombre = nombre;
        this.ventana = parent;
        this.nombre = nombre;
        initComponents();
        llenarCategorias();
        if (opcion == 0) {
            jButton1.setText("Agregar");
        }else{
            jButton1.setText("Modificar");
            jTextField1.setText(nombre);
            clases.Producto tmp = ManipulaCarrito.buscaNombreProducto(productos, nombre);
            jComboBoxCategoria.setSelectedItem(tmp.getCategoria());
            jTextField2.setText(String.valueOf(tmp.getPrecio()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Categoria:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Precio:");

        jButton1.setText("Instruccion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(4, 4, 4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (opcion == 0) {
            if (jTextField1.getText().length() > 0 && jTextField2.getText().length() > 0) {
                productos.add(new clases.Producto(jTextField1.getText(), (String)jComboBoxCategoria.getSelectedItem(), Double.valueOf(jTextField2.getText())));
                ManipulaArchivos.guarda("productos.dat", productos);
                JOptionPane.showMessageDialog(this, "Producto dado de alta");
                jTextField1.setText("");
                jTextField2.setText("");
                this.dispose();
                new JDialogProducto(ventana, true, productos, categorias, true).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Falta ingresar datos");
            }
        }else{
            clases.Producto tmp = ManipulaCarrito.buscaNombreProducto(productos, nombre);
            int confirm = 1;
            if (productos.size() > 0) {
                confirm = JOptionPane.showConfirmDialog(null,
                        ("¿Seguro que desea modificar el producto " + tmp.getNombreProducto()+ "?\n"
                                + "Datos finales del producto:\n"
                                + "Nombre de productos: "+jTextField1.getText() + "\n"
                                + "Categoria: "+(String)jComboBoxCategoria.getSelectedItem() + "\n"
                                + "Precio: "+jTextField2.getText()),
                        "Confirmación de Baja",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);
            }
            if (confirm == 0) {
                tmp.setNombreProducto(jTextField1.getText());
                tmp.setCategoria((String)jComboBoxCategoria.getSelectedItem());
                tmp.setPrecio(Double.valueOf(jTextField2.getText()));
                JOptionPane.showMessageDialog(this, "Productos Modificado");
                ManipulaArchivos.guarda("productos.dat", productos);
                jTextField1.setText("");
                jTextField2.setText("");
                this.dispose();
                new JDialogProducto(ventana, true, productos, categorias, true).setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    void llenarCategorias() {
        herramientas.ManipulaCarrito.llenarCombo(categorias, jComboBoxCategoria);
    }
}
