/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import cjb.ci.Validaciones;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class JDialogAccesoAdmin extends javax.swing.JDialog {

    JFrame inicio;
    ArrayList <clases.Empleado> empleados;
    ArrayList <clases.Venta> ventas;
    ArrayList <clases.Producto> productos;
    String categorias[];
    int opcion;
    String pin;
    
    /**
     * Creates new form AccesoAdmin
     */
    public JDialogAccesoAdmin(java.awt.Frame parent, boolean modal, JFrame inicio, ArrayList <clases.Empleado> empleados, ArrayList <clases.Venta> ventas, ArrayList <clases.Producto> productos, String categorias[],String pin, int opcion) {
        super(parent, modal);
        this.inicio = inicio;
        this.empleados = empleados;
        this.ventas = ventas;
        this.productos = productos;
        this.categorias = categorias;
        this.opcion = opcion;
        this.pin = pin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ingrese PIN de Administrador");

        jButtonIngresar.setText("Aceptar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonIngresar)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIngresar)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        if (jPasswordField1.getText().length() != 0) {
            if (jPasswordField1.getText().equals(pin)) {
                if (opcion == 1) {
                    this.dispose();
                    herramientas.HerramientasInterfaz.addPanel(inicio, new JPanelEmpleado(inicio, empleados, true, ventas), "Administración de Empleados", false);
                }else{
                    this.dispose();
                    new JDialogProducto(inicio, true, productos, categorias, true).setVisible(true);
                }
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "PIN invalido, por favor ingrese de nuevo");
            }
            jPasswordField1.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "debe ingresar un PIN antes de continuar");
        }
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jPasswordField1.getText().length() != 0) {
                if (jPasswordField1.getText().equals(pin)) {
                    if (opcion == 1) {
                        herramientas.HerramientasInterfaz.addPanel(inicio, new JPanelEmpleado(inicio, empleados, true, ventas), "Administración de Empleados", false);
                    }else{
                        new JDialogProducto(inicio, true, productos, categorias, true).setVisible(true);
                    }
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "PIN invalido, por favor ingrese de nuevo");
                }
                jPasswordField1.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "debe ingresar un PIN antes de continuar");
            }
            jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
