/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Venta;
import java.util.ArrayList;

/**
 *
 * @author USER
 */
public class JDialogVentaDiaria extends javax.swing.JDialog {

    ArrayList <clases.Venta> ventas;
    double fondoCaja;
    String fecha;
    /**
     * Creates new form JDialogVentaDiaria
     */
    public JDialogVentaDiaria(java.awt.Frame parent, boolean modal, ArrayList <clases.Venta> ventas, double fondoCaja, String fecha) {
        super(parent, modal);
        initComponents();
        this.ventas = ventas;
        this.fondoCaja = fondoCaja;
        this.fecha = fecha;
        jTextFieldFondoCaja.setText(String.valueOf(fondoCaja));
        jTextFieldCajaActual.setText(String.valueOf(fondoCaja+llenaVenta(ventas)));
        jTextFieldVentaTotal.setText(String.valueOf(llenaVenta(ventas)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldFondoCaja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldVentaTotal = new javax.swing.JTextField();
        jTextFieldCajaActual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fondo de Caja");

        jTextFieldFondoCaja.setEditable(false);

        jLabel2.setText("Venta Total");

        jTextFieldVentaTotal.setEditable(false);

        jTextFieldCajaActual.setEditable(false);

        jLabel3.setText("Caja Actual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldFondoCaja)
                    .addComponent(jTextFieldCajaActual)
                    .addComponent(jTextFieldVentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldFondoCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCajaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldVentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public double llenaVenta(ArrayList <clases.Venta> ventas){
        double ventTotal = 0.0;
        if (ventas.size() > 0) {
            for (Venta venta : ventas) {
                if (venta.getFecha().equals(fecha)) {
                    ventTotal = ventTotal + (Double.valueOf(venta.getTotal()));
                }
            }
            return ventTotal;
        }
        return ventTotal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldCajaActual;
    private javax.swing.JTextField jTextFieldFondoCaja;
    private javax.swing.JTextField jTextFieldVentaTotal;
    // End of variables declaration//GEN-END:variables
}
