/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import clases.ProductoVenta;
import clases.Venta;
import herramientas.ManipulaArchivos;
import herramientas.ManipulaEmpleados;
import herramientas.ManipulaMesas;
import herramientas.ManipulaVenta;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edenj
 */
public class JPanelCarrito extends javax.swing.JPanel {
    String fecha;
    clases.Mesa mesas[];
    ArrayList <clases.Producto> productos;
    String categorias[];
    ArrayList <clases.Empleado> empleados;
    ArrayList <clases.Venta> ventas;
    JFrame ventana;
    JLabel labelIconMesaSelect;
    Icon iconMesaNormal = new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"));
    Icon iconMesaSelect = new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesaSelect.png"));
    clases.Mesa mesaActual = null;
    int folio;
    
    /**
     * Creates new form JPanelCarrito
     */
    public JPanelCarrito(String fecha, JFrame ventana, clases.Mesa mesas[], String categorias[], ArrayList <clases.Producto> productos, ArrayList <clases.Empleado> empleados, ArrayList <clases.Venta> ventas) {
        this.fecha = fecha;
        this.mesas = mesas;
        this.ventana = ventana;
        this.empleados = empleados;
        this.ventas = ventas;
        this.categorias = categorias;
        this.productos = productos;
        this.folio = (int)ManipulaArchivos.cargaNum("folios.dat");
        initComponents();
        jTableProductos.getTableHeader().setReorderingAllowed(false);
        jLabelFechaEdit.setText(fecha);
        ManipulaEmpleados.llenarCombo(empleados, jComboBoxMeseros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFecha = new javax.swing.JLabel();
        jLabelFechaEdit = new javax.swing.JLabel();
        jLabelMesero = new javax.swing.JLabel();
        jComboBoxMeseros = new javax.swing.JComboBox<>();
        jLabelNComensales = new javax.swing.JLabel();
        jSpinnerNComensales = new javax.swing.JSpinner();
        jButtonMoverMesa = new javax.swing.JButton();
        jLabelIconME1 = new javax.swing.JLabel();
        jLabelME1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jButtonCerrarVenta = new javax.swing.JButton();
        jLabelIconME2 = new javax.swing.JLabel();
        jLabelME2 = new javax.swing.JLabel();
        jSeparatorM1 = new javax.swing.JSeparator();
        jLabelIconMS1 = new javax.swing.JLabel();
        jLabelMS1 = new javax.swing.JLabel();
        jLabelIconMS2 = new javax.swing.JLabel();
        jLabelMS2 = new javax.swing.JLabel();
        jLabelMS4 = new javax.swing.JLabel();
        jLabelIconMS3 = new javax.swing.JLabel();
        jLabelMS3 = new javax.swing.JLabel();
        jLabelIconMS4 = new javax.swing.JLabel();
        jSeparatorM2 = new javax.swing.JSeparator();
        jLabelIconMS5 = new javax.swing.JLabel();
        jLabelMS5 = new javax.swing.JLabel();
        jLabelIconMS6 = new javax.swing.JLabel();
        jLabelMS6 = new javax.swing.JLabel();
        jLabelIconMJ1 = new javax.swing.JLabel();
        jLabelMJ1 = new javax.swing.JLabel();
        jLabelIconMJ2 = new javax.swing.JLabel();
        jLabelMJ2 = new javax.swing.JLabel();
        jLabelIconMJ3 = new javax.swing.JLabel();
        jLabelMJ3 = new javax.swing.JLabel();
        jButtonAgregarProducto = new javax.swing.JButton();
        jLabelMesaSeleccionada = new javax.swing.JLabel();
        jTextFieldMesaSeleccionada = new javax.swing.JTextField();
        jButtonEliminarProducto = new javax.swing.JButton();

        jLabelFecha.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jLabelFecha.setText("Fecha:");

        jLabelMesero.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jLabelMesero.setText("Mesero:");

        jComboBoxMeseros.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jComboBoxMeseros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMeserosItemStateChanged(evt);
            }
        });

        jLabelNComensales.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jLabelNComensales.setText("No. Comensales:");

        jSpinnerNComensales.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jSpinnerNComensales.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerNComensales.setEnabled(false);
        jSpinnerNComensales.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerNComensalesStateChanged(evt);
            }
        });

        jButtonMoverMesa.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jButtonMoverMesa.setForeground(new java.awt.Color(102, 0, 0));
        jButtonMoverMesa.setText("Mover Mesa");
        jButtonMoverMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoverMesaActionPerformed(evt);
            }
        });

        jLabelIconME1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconME1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconME1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconME1.setText("M - E1");
        jLabelIconME1.setToolTipText("E1");
        jLabelIconME1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconME1MouseClicked(evt);
            }
        });

        jLabelME1.setLabelFor(jLabelIconME1);
        jLabelME1.setText("M - E1");
        jLabelME1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelME1MouseClicked(evt);
            }
        });

        jTableProductos.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Producto", "Precio C/U", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableProductosPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableProductos.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableProductos.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jTextFieldTotal.setText("0.00");

        jLabelTotal.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jLabelTotal.setText("Total:");

        jButtonCerrarVenta.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jButtonCerrarVenta.setForeground(new java.awt.Color(102, 0, 0));
        jButtonCerrarVenta.setText("Imprimir Nota");
        jButtonCerrarVenta.setEnabled(false);
        jButtonCerrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarVentaActionPerformed(evt);
            }
        });

        jLabelIconME2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconME2.setToolTipText("E1");
        jLabelIconME2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconME2MouseClicked(evt);
            }
        });

        jLabelME2.setLabelFor(jLabelIconME1);
        jLabelME2.setText("M - E2");
        jLabelME2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelME2MouseClicked(evt);
            }
        });

        jLabelIconMS1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconMS1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconMS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconMS1.setText("M - E1");
        jLabelIconMS1.setToolTipText("E1");
        jLabelIconMS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMS1MouseClicked(evt);
            }
        });

        jLabelMS1.setLabelFor(jLabelIconME1);
        jLabelMS1.setText("M - S1");
        jLabelMS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMS1MouseClicked(evt);
            }
        });

        jLabelIconMS2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconMS2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconMS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconMS2.setToolTipText("E1");
        jLabelIconMS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMS2MouseClicked(evt);
            }
        });

        jLabelMS2.setLabelFor(jLabelIconME1);
        jLabelMS2.setText("M - S2");
        jLabelMS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMS2MouseClicked(evt);
            }
        });

        jLabelMS4.setLabelFor(jLabelIconME1);
        jLabelMS4.setText("M - S4");
        jLabelMS4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMS4MouseClicked(evt);
            }
        });

        jLabelIconMS3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconMS3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconMS3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconMS3.setText("M - E1");
        jLabelIconMS3.setToolTipText("E1");
        jLabelIconMS3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMS3MouseClicked(evt);
            }
        });

        jLabelMS3.setLabelFor(jLabelIconME1);
        jLabelMS3.setText("M - S3");
        jLabelMS3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMS3MouseClicked(evt);
            }
        });

        jLabelIconMS4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconMS4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconMS4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconMS4.setToolTipText("E1");
        jLabelIconMS4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMS4MouseClicked(evt);
            }
        });

        jLabelIconMS5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconMS5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconMS5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconMS5.setText("M - E1");
        jLabelIconMS5.setToolTipText("E1");
        jLabelIconMS5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMS5MouseClicked(evt);
            }
        });

        jLabelMS5.setLabelFor(jLabelIconME1);
        jLabelMS5.setText("M - S5");
        jLabelMS5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMS5MouseClicked(evt);
            }
        });

        jLabelIconMS6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconMS6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconMS6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconMS6.setToolTipText("E1");
        jLabelIconMS6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMS6MouseClicked(evt);
            }
        });

        jLabelMS6.setLabelFor(jLabelIconME1);
        jLabelMS6.setText("M - S6");
        jLabelMS6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMS6MouseClicked(evt);
            }
        });

        jLabelIconMJ1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconMJ1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconMJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconMJ1.setToolTipText("E1");
        jLabelIconMJ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMJ1MouseClicked(evt);
            }
        });

        jLabelMJ1.setLabelFor(jLabelIconME1);
        jLabelMJ1.setText("M - J1");
        jLabelMJ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMJ1MouseClicked(evt);
            }
        });

        jLabelIconMJ2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconMJ2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconMJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconMJ2.setToolTipText("E1");
        jLabelIconMJ2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMJ2MouseClicked(evt);
            }
        });

        jLabelMJ2.setLabelFor(jLabelIconME1);
        jLabelMJ2.setText("M - J2");
        jLabelMJ2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMJ2MouseClicked(evt);
            }
        });

        jLabelIconMJ3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIconMJ3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIconMJ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carritoMesa.png"))); // NOI18N
        jLabelIconMJ3.setToolTipText("E1");
        jLabelIconMJ3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMJ3MouseClicked(evt);
            }
        });

        jLabelMJ3.setLabelFor(jLabelIconME1);
        jLabelMJ3.setText("M - J3");
        jLabelMJ3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMJ3MouseClicked(evt);
            }
        });

        jButtonAgregarProducto.setFont(new java.awt.Font("Consolas", 2, 12)); // NOI18N
        jButtonAgregarProducto.setForeground(new java.awt.Color(0, 51, 0));
        jButtonAgregarProducto.setText("Agregar Producto");
        jButtonAgregarProducto.setEnabled(false);
        jButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProductoActionPerformed(evt);
            }
        });

        jLabelMesaSeleccionada.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        jLabelMesaSeleccionada.setText("Mesa Seleccionada: ");

        jTextFieldMesaSeleccionada.setEditable(false);
        jTextFieldMesaSeleccionada.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jTextFieldMesaSeleccionada.setForeground(new java.awt.Color(153, 0, 0));
        jTextFieldMesaSeleccionada.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonEliminarProducto.setFont(new java.awt.Font("Consolas", 2, 12)); // NOI18N
        jButtonEliminarProducto.setForeground(new java.awt.Color(102, 0, 0));
        jButtonEliminarProducto.setText("Eliminar Producto");
        jButtonEliminarProducto.setEnabled(false);
        jButtonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAgregarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMesero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxMeseros, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNComensales))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFecha)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelFechaEdit)))
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerNComensales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMesaSeleccionada)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMesaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMoverMesa))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCerrarVenta)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparatorM1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelME2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelIconME2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelME1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelIconME1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(52, 52, 52))
                        .addComponent(jSeparatorM2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMJ1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelIconMJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMJ3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelIconMJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMJ2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelIconMJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelMS4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelIconMS4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelMS3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelIconMS3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelMS1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelIconMS1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelMS2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelIconMS2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMS5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelIconMS5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMS6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelIconMS6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(44, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jLabelFechaEdit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMeseros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNComensales, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerNComensales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMesaSeleccionada)
                    .addComponent(jTextFieldMesaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMoverMesa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarProducto)
                    .addComponent(jButtonEliminarProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIconME1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelME1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIconME2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelME2)))
                .addGap(30, 30, 30)
                .addComponent(jSeparatorM1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelIconMS1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMS1))
                    .addComponent(jLabelIconMS2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMS2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIconMS3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMS3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIconMS4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMS4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelIconMS5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMS5))
                    .addComponent(jLabelIconMS6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMS6)))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorM2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIconMJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMJ2))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIconMJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMJ1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIconMJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMJ3)
                                    .addComponent(jButtonCerrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelIconME1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconME1MouseClicked
        abrirMesa("E1", jLabelIconME1);
    }//GEN-LAST:event_jLabelIconME1MouseClicked

    private void jLabelIconME2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconME2MouseClicked
        abrirMesa("E2", jLabelIconME2);
    }//GEN-LAST:event_jLabelIconME2MouseClicked

    private void jLabelME2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelME2MouseClicked
        jLabelIconME2MouseClicked(null);
    }//GEN-LAST:event_jLabelME2MouseClicked

    private void jLabelME1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelME1MouseClicked
        jLabelIconME1MouseClicked(null);
    }//GEN-LAST:event_jLabelME1MouseClicked

    private void jLabelIconMS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMS1MouseClicked
        abrirMesa("S1", jLabelIconMS1);
    }//GEN-LAST:event_jLabelIconMS1MouseClicked

    private void jLabelMS1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMS1MouseClicked
        jLabelIconMS1MouseClicked(null);
    }//GEN-LAST:event_jLabelMS1MouseClicked

    private void jLabelIconMS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMS2MouseClicked
        abrirMesa("S2", jLabelIconMS2);
    }//GEN-LAST:event_jLabelIconMS2MouseClicked

    private void jLabelMS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMS2MouseClicked
        jLabelIconMS2MouseClicked(null);
    }//GEN-LAST:event_jLabelMS2MouseClicked

    private void jLabelMS4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMS4MouseClicked
        jLabelIconMS4MouseClicked(null);
    }//GEN-LAST:event_jLabelMS4MouseClicked

    private void jLabelIconMS3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMS3MouseClicked
        abrirMesa("S3", jLabelIconMS3);
    }//GEN-LAST:event_jLabelIconMS3MouseClicked

    private void jLabelMS3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMS3MouseClicked
        jLabelIconMS3MouseClicked(null);
    }//GEN-LAST:event_jLabelMS3MouseClicked

    private void jLabelIconMS4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMS4MouseClicked
        abrirMesa("S4", jLabelIconMS4);
    }//GEN-LAST:event_jLabelIconMS4MouseClicked

    private void jLabelIconMS5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMS5MouseClicked
        abrirMesa("S5", jLabelIconMS5);
    }//GEN-LAST:event_jLabelIconMS5MouseClicked

    private void jLabelMS5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMS5MouseClicked
        jLabelIconMS5MouseClicked(null);
    }//GEN-LAST:event_jLabelMS5MouseClicked

    private void jLabelIconMS6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMS6MouseClicked
        abrirMesa("S6", jLabelIconMS6);
    }//GEN-LAST:event_jLabelIconMS6MouseClicked

    private void jLabelMS6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMS6MouseClicked
        jLabelIconMS6MouseClicked(null);
    }//GEN-LAST:event_jLabelMS6MouseClicked

    private void jLabelIconMJ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMJ1MouseClicked
        abrirMesa("J1", jLabelIconMJ1);
    }//GEN-LAST:event_jLabelIconMJ1MouseClicked

    private void jLabelMJ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMJ1MouseClicked
        jLabelIconMJ1MouseClicked(null);
    }//GEN-LAST:event_jLabelMJ1MouseClicked

    private void jLabelIconMJ2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMJ2MouseClicked
        abrirMesa("J2", jLabelIconMJ2);
    }//GEN-LAST:event_jLabelIconMJ2MouseClicked

    private void jLabelMJ2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMJ2MouseClicked
        jLabelIconMJ2MouseClicked(null);
    }//GEN-LAST:event_jLabelMJ2MouseClicked

    private void jLabelIconMJ3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMJ3MouseClicked
        jLabelMJ3MouseClicked(null);
    }//GEN-LAST:event_jLabelIconMJ3MouseClicked

    private void jLabelMJ3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMJ3MouseClicked
        abrirMesa("J3", jLabelIconMJ3);
    }//GEN-LAST:event_jLabelMJ3MouseClicked

    private void jButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoActionPerformed
        new JDialogCarritoAgregarProducto(ventana, true, mesaActual, productos, categorias).setVisible(true);
        abrirMesa(mesaActual.getNombre(), null);
    }//GEN-LAST:event_jButtonAgregarProductoActionPerformed

    private void jTableProductosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableProductosPropertyChange
        int fila = jTableProductos.getSelectedRow();
        int columna = jTableProductos.getSelectedColumn();
        if (fila >= 0 && columna >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) jTableProductos.getModel();
            String cantidadtmp = modelo.getValueAt(fila, columna).toString();
            int cantidad = Integer.parseInt(cantidadtmp);
            if (cantidad > 0) {
                mesaActual.getProductos().get(fila).setCantidad(cantidad);
            }
            abrirMesa(mesaActual.getNombre(), null);
        }
    }//GEN-LAST:event_jTableProductosPropertyChange

    private void jButtonCerrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarVentaActionPerformed
        String hora = (DateTimeFormatter.ofPattern("HH:mm")).format(LocalDateTime.now());
        clases.Mesa tmp = ManipulaMesas.obtenerMesa(mesas, jTextFieldMesaSeleccionada.getText());
        tmp.setMesero((String)jComboBoxMeseros.getSelectedItem());
        String total = jTextFieldTotal.getText();

        clases.Venta vnt = new Venta(folio, fecha, hora, tmp, total);
        
        folio = folio + ((int) ManipulaArchivos.cargaNum("aumento.dat"));

        ManipulaArchivos.guarda("folios.dat", folio);
        
        String nota = ManipulaVenta.venta(vnt);
        String ticket = ManipulaVenta.nota(nota);
        FileWriter salida = null;
        try {
            salida = new FileWriter("E:/Documents/notas.txt");
            salida.write(ticket);
            salida.close();
//            Desktop.getDesktop().print(new File("E:/Documents/notas.txt"));
            Desktop.getDesktop().open(new File("E:/Documents/notas.txt"));
        } catch (IOException ex) {
            poo.JOPMensaje.error(this, "La nota no fue generada correctamente");
        }
        (new JDialogCerrarVenta(tmp, ventas, folio, ventana, true, nota, vnt)).setVisible(true);
        folio = (int)ManipulaArchivos.cargaNum("folios.dat");
        abrirMesa(mesaActual.getNombre(), null);
    }//GEN-LAST:event_jButtonCerrarVentaActionPerformed

    private void jButtonMoverMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoverMesaActionPerformed
        String nombre = poo.JOPMensaje.pedir(this, "La mesa a la que desea moverse es M - :");
        if (nombre != null) {
            nombre = nombre.toUpperCase();
            clases.Mesa tmp = ManipulaMesas.obtenerMesa(mesas, nombre);
            if (tmp != null) {
                if (tmp.getProductos().isEmpty()) {
                    tmp.setProductos((ArrayList<ProductoVenta>) mesaActual.getProductos().clone());
                    mesaActual.getProductos().clear();
                    poo.JOPMensaje.exito(this, "Se movió correctamente de mesa");
                    abrirMesa(tmp.getNombre(), null);
                } else {
                    poo.JOPMensaje.error(this, "La mesa a la que desea moverse esta ocupada");
                }
            } else {
                poo.JOPMensaje.error(this, "La mesa no se encontró, favor de revisar el dato");
            }
        }
    }//GEN-LAST:event_jButtonMoverMesaActionPerformed

    private void jButtonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProductoActionPerformed
        int fila = jTableProductos.getSelectedRow();
        if (fila >= 0) {
            int siOno = poo.JOPMensaje.pregunta(this, "¿Desea borrar el producto por completo?");
            if (siOno == 0) {
                mesaActual.getProductos().remove(fila);
                poo.JOPMensaje.exito(this, "Se eliminó el producto por completo");
            } else if (siOno == 1) {
                int cantidad = mesaActual.getProductos().get(fila).getCantidad();
                String cantidadS = poo.JOPMensaje.pedir(this, "Ingrese la cantidad que desea eliminar, la cantidad actual es de: " + cantidad);
                try {
                    int cantidadTmp = Integer.parseInt(cantidadS);
                    if (cantidadTmp < cantidad) {
                        mesaActual.getProductos().get(fila).setCantidad(cantidad - cantidadTmp);
                        poo.JOPMensaje.exito(this, "Se eliminó la cantidad ingresada");
                    } else if (cantidadTmp == cantidad) {
                        mesaActual.getProductos().remove(fila);
                        poo.JOPMensaje.exito(this, "Se eliminó el producto por completo");
                    } else {
                        poo.JOPMensaje.error(this, "Favor de ingresar una cantidad menor a la actual");
                    }
                } catch (Exception e) {
                    poo.JOPMensaje.error(this, "Favor de ingresar una cantidad válida");
                }
            }
            abrirMesa(mesaActual.getNombre(), null);
        }
    }//GEN-LAST:event_jButtonEliminarProductoActionPerformed

    private void jComboBoxMeserosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMeserosItemStateChanged
        OtorgarMesero(jComboBoxMeseros, jTextFieldMesaSeleccionada.getText());
    }//GEN-LAST:event_jComboBoxMeserosItemStateChanged

    private void jSpinnerNComensalesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerNComensalesStateChanged
        NComensales(jSpinnerNComensales, jTextFieldMesaSeleccionada.getText());
    }//GEN-LAST:event_jSpinnerNComensalesStateChanged
    /**
     * Método que nos permite abrir una mesa y mostrarla en el JTable del panel.
     *
     * @param nombreMesa String con el nombre de la mesa a abrir.
     * @param iconMesa JLabel con el icono de la mesa, en caso de null se salta
     * esta parte.
     */
    public void abrirMesa(String nombreMesa, JLabel iconMesa) {
        if (labelIconMesaSelect != null) {
            labelIconMesaSelect.setIcon(iconMesaNormal);
        }
        if (iconMesa != null) {
            labelIconMesaSelect = iconMesa;
            iconMesa.setIcon(iconMesaSelect);
        }
        jTextFieldMesaSeleccionada.setText(nombreMesa);
        clases.Mesa tmp = ManipulaMesas.obtenerMesa(mesas, nombreMesa);
        if (tmp != null) {
            jTableProductos.clearSelection();
            mesaActual = tmp;
            double total = herramientas.ManipulaCarrito.mostrarProducto(jTableProductos, mesaActual.getProductos());
            jTextFieldTotal.setText("" + total);
            jSpinnerNComensales.setValue(mesaActual.getComensales());
            jComboBoxMeseros.setSelectedItem(mesaActual.getMesero());
        } else {
            herramientas.ManipulaCarrito.limpiarFilasJTable(jTableProductos);
            jTextFieldTotal.setText("0.00");
        }
        jButtonAgregarProducto.setEnabled(mesaActual != null);
        jButtonEliminarProducto.setEnabled(mesaActual != null);
        jButtonCerrarVenta.setEnabled(tmp.getProductos().size() != 0);
        jSpinnerNComensales.setEnabled(mesaActual != null);
    }
    
    private void OtorgarMesero(JComboBox meseros, String nombreMesa) {
        if (nombreMesa.length() != 0) {
            String mesero = (String) meseros.getSelectedItem();
            (ManipulaMesas.obtenerMesa(mesas, nombreMesa)).setMesero(mesero);
        }
    }
    
    private void NComensales(JSpinner comen, String nombreMesa){
        if (nombreMesa.length() != 0) {
            int comensales = (int)comen.getValue();
            (ManipulaMesas.obtenerMesa(mesas, nombreMesa)).setComensales(comensales);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonCerrarVenta;
    private javax.swing.JButton jButtonEliminarProducto;
    private javax.swing.JButton jButtonMoverMesa;
    private javax.swing.JComboBox<String> jComboBoxMeseros;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFechaEdit;
    private javax.swing.JLabel jLabelIconME1;
    private javax.swing.JLabel jLabelIconME2;
    private javax.swing.JLabel jLabelIconMJ1;
    private javax.swing.JLabel jLabelIconMJ2;
    private javax.swing.JLabel jLabelIconMJ3;
    private javax.swing.JLabel jLabelIconMS1;
    private javax.swing.JLabel jLabelIconMS2;
    private javax.swing.JLabel jLabelIconMS3;
    private javax.swing.JLabel jLabelIconMS4;
    private javax.swing.JLabel jLabelIconMS5;
    private javax.swing.JLabel jLabelIconMS6;
    private javax.swing.JLabel jLabelME1;
    private javax.swing.JLabel jLabelME2;
    private javax.swing.JLabel jLabelMJ1;
    private javax.swing.JLabel jLabelMJ2;
    private javax.swing.JLabel jLabelMJ3;
    private javax.swing.JLabel jLabelMS1;
    private javax.swing.JLabel jLabelMS2;
    private javax.swing.JLabel jLabelMS3;
    private javax.swing.JLabel jLabelMS4;
    private javax.swing.JLabel jLabelMS5;
    private javax.swing.JLabel jLabelMS6;
    private javax.swing.JLabel jLabelMesaSeleccionada;
    private javax.swing.JLabel jLabelMesero;
    private javax.swing.JLabel jLabelNComensales;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorM1;
    private javax.swing.JSeparator jSeparatorM2;
    private javax.swing.JSpinner jSpinnerNComensales;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldMesaSeleccionada;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
