/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import herramientas.ManipulaArchivos;
import herramientas.ManipulaEmpleados;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class JPanelEmpleado extends javax.swing.JPanel {
    
    ArrayList <clases.Empleado> empleados;
    ArrayList <clases.Venta> ventas;
    boolean admin;
    String pin = "";
    JFrame ventana;
    /**
     * Creates new form JPanelEmpleado
     */
    public JPanelEmpleado(JFrame ventana, ArrayList <clases.Empleado> empleados, boolean admin, ArrayList <clases.Venta> ventas) {
        this.empleados = empleados;
        this.admin = admin;
        this.ventana = ventana;
        this.ventas = ventas;
        initComponents();
        jLabelIconIzq.setVisible(!(admin));
        jLabelNombre.setVisible(admin);
        jLabelPin.setVisible(admin);
        jLabelHoraEntrada.setVisible(admin);
        jLabelDosPuntos.setVisible(admin);
        jComboBoxHoras.setVisible(admin);
        jComboBoxMinutos.setVisible(admin);
        jTextFieldNombre.setVisible(admin);
        jPasswordField1.setVisible(admin);
        jButtonAgregar.setVisible(admin);
        jButtonPagoNomina.setVisible(admin);
        jButtonModificar.setVisible(admin);
        ManipulaEmpleados.llenarCombo(empleados, jComboBoxEmpleados);
        if (!empleados.isEmpty()) {
            jButtonModificar.setEnabled(true);
            jButtonElimina.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIconDer = new javax.swing.JLabel();
        jLabelPin = new javax.swing.JLabel();
        jComboBoxEmpleados = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBoxMinutos = new javax.swing.JComboBox<>();
        jLabelHoraEntrada = new javax.swing.JLabel();
        jComboBoxHoras = new javax.swing.JComboBox<>();
        jLabelDosPuntos = new javax.swing.JLabel();
        jButtonPagoNomina = new javax.swing.JButton();
        jButtonConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsulta = new javax.swing.JTextArea();
        jButtonAgregar = new javax.swing.JButton();
        jLabelIconIzq = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonModificar = new javax.swing.JButton();
        jButtonElimina = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(782, 535));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/barista.png"))); // NOI18N
        add(jLabelIconDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabelPin.setText("PIN:");
        add(jLabelPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jComboBoxEmpleados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEmpleadosItemStateChanged(evt);
            }
        });
        add(jComboBoxEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 65, 170, -1));

        jLabelNombre.setText("Nombre:");
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 130, 130, -1));

        jComboBoxMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        add(jComboBoxMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabelHoraEntrada.setText("Hora de Entrada:");
        add(jLabelHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jComboBoxHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));
        add(jComboBoxHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabelDosPuntos.setText(":");
        add(jLabelDosPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jButtonPagoNomina.setText("Pago de Nomina");
        jButtonPagoNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagoNominaActionPerformed(evt);
            }
        });
        add(jButtonPagoNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        jButtonConsulta.setText("Consultar");
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });
        add(jButtonConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 96, -1, -1));

        jTextAreaConsulta.setEditable(false);
        jTextAreaConsulta.setColumns(20);
        jTextAreaConsulta.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsulta);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 130, 290, 208));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 325, -1, -1));

        jLabelIconIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/barista.png"))); // NOI18N
        add(jLabelIconIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));

        jButtonModificar.setText("Modificar");
        jButtonModificar.setEnabled(false);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 80, -1));

        jButtonElimina.setText("Eliminar");
        jButtonElimina.setEnabled(false);
        jButtonElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminaActionPerformed(evt);
            }
        });
        add(jButtonElimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String pin = jPasswordField1.getText();
        String nombre = jTextFieldNombre.getText().toUpperCase();
        String hora_Entrada = (String)jComboBoxHoras.getSelectedItem()+":"+(String)jComboBoxMinutos.getSelectedItem();
        int itemH = jComboBoxHoras.getSelectedIndex();
        int itemM = jComboBoxMinutos.getSelectedIndex();
        if (itemM >= 50) {
            itemH += 1;
            itemM = 10 - (60 - itemM);
        } else {
            itemM += 10;
        }
        String hora_limite = (String) jComboBoxHoras.getItemAt(itemH) + ":" + (String) jComboBoxMinutos.getItemAt(itemM);
        if (nombre.length() != 0 && pin.length() != 0) {
            clases.Empleado tmp = ManipulaEmpleados.buscaEmpleado(empleados, nombre);
            if (tmp != null) {
                JOptionPane.showMessageDialog(this, "Ya se ha ingresado ese nombre en los registros");
                jTextFieldNombre.setText("");
                CtrlInterfaz.cambia(jTextFieldNombre);
            } else {
                int pinTemp = Integer.valueOf(pin);
                empleados.add(new clases.Empleado(nombre, false, pinTemp, hora_Entrada, hora_limite, 0));
                ManipulaEmpleados.llenarCombo(empleados, jComboBoxEmpleados);
                jTextFieldNombre.setText("");
                jPasswordField1.setText("");
                jComboBoxHoras.setSelectedIndex(0);
                jComboBoxMinutos.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "Empleado dado de Alta");
                ManipulaArchivos.guarda("empleados.dat", empleados);
                jButtonModificar.setEnabled(true);
                jButtonElimina.setEnabled(true);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Falta ingresar datos");
        }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed
        clases.Empleado tmp = ManipulaEmpleados.buscaEmpleado(empleados, (String)jComboBoxEmpleados.getSelectedItem());
        if (tmp != null) {
            String nombre = "Nombre: " + tmp.getNombre();
            String ingreso;
            if (tmp.getIngreso()) {
                ingreso = "\nStatus: Ya ha entrado a turno";
            }else{
                ingreso = "\nStatus: No ha entrado a turno";
            }
            String pin = "\nPIN: " + ManipulaEmpleados.encriptar(String.valueOf(tmp.getPin()));
            String horaEntrada = "\nHora de Entrada: " + tmp.getHoraEntrada();
            String horaLimite = "\nHora Limite de entrada: " + tmp.getHoraLimite();
            String retardos = "\nRetardos semanales: " + String.valueOf(tmp.getRetardos());
            jTextAreaConsulta.setText(nombre + ingreso + pin + horaEntrada + horaLimite + retardos);
        }
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void jComboBoxEmpleadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEmpleadosItemStateChanged
        jTextAreaConsulta.setText("");
    }//GEN-LAST:event_jComboBoxEmpleadosItemStateChanged

    private void jButtonPagoNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagoNominaActionPerformed
        new JDialogPagoNomina(ventana, true, empleados, ventas).setVisible(true);
    }//GEN-LAST:event_jButtonPagoNominaActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        Validaciones.validaEntero(evt);
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            CtrlInterfaz.cambia(jPasswordField1);
        }
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        new JDialogModificarEmpleado(ventana, true, empleados).setVisible(true);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminaActionPerformed
        clases.Empleado tmp = ManipulaEmpleados.buscaEmpleado(empleados, (String)jComboBoxEmpleados.getSelectedItem());
        int confirm = 1;
        if (empleados.size() > 0) {
            confirm = JOptionPane.showConfirmDialog(null, 
                    ("¿Seguro que desea dar de baja al empleado "+tmp.getNombre()+"?"),
                    "Confirmación de Baja",
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.WARNING_MESSAGE);
        }
        if (confirm == 0) {
            empleados.remove(tmp);
            JOptionPane.showMessageDialog(this, "Empleado Dado de Baja");
            jTextAreaConsulta.setText("");
            ManipulaArchivos.guarda("empleados.dat", empleados);
        }
        if (empleados.isEmpty()) {
            jButtonModificar.setEnabled(false);
            jButtonElimina.setEnabled(false);
        }
        ManipulaEmpleados.llenarCombo(empleados, jComboBoxEmpleados);
    }//GEN-LAST:event_jButtonEliminaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonElimina;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonPagoNomina;
    private javax.swing.JComboBox<String> jComboBoxEmpleados;
    private javax.swing.JComboBox<String> jComboBoxHoras;
    private javax.swing.JComboBox<String> jComboBoxMinutos;
    private javax.swing.JLabel jLabelDosPuntos;
    private javax.swing.JLabel jLabelHoraEntrada;
    private javax.swing.JLabel jLabelIconDer;
    private javax.swing.JLabel jLabelIconIzq;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPin;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaConsulta;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
